# Generated by Django 4.1.3 on 2022-12-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_done',
        ),
    ]
